name: Validate workflow file syntax
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/*
  pull_request:
    paths:
      - .github/workflows/*
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  action-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: .github/workflows
      - uses: mpalmer/action-validator@c994f427b7c42cd5ecb1bc9315cb91c3d7d72e3d
        with:
          version: 0.9.0
