# SPDX-FileCopyrightText: © 2024 Kevin Lu
# SPDX-Licence-Identifier: AGPL-3.0-or-later
name: Validate vector.json
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/validate-vector.yaml
      - src/validate.py
      - data/**
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/validate-vector.yaml
      - src/validate.py
      - data/**
  workflow_dispatch:
jobs:
  validate-vector:
    name: Validate vector.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: src/requirements.txt
      - run: pip install -r src/requirements.txt
      - run: python src/validate.py
